//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutricloud_webforms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estilo_vida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estilo_vida()
        {
            this.usuario_estilo_vida = new HashSet<usuario_estilo_vida>();
        }
    
        public int id_estilo_de_vida { get; set; }
        public byte[] estilo_de_vida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_estilo_vida> usuario_estilo_vida { get; set; }
    }
}
