//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutricloud_webforms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_estilo_vida
    {
        public int id_estilo_de_vida { get; set; }
        public byte[] estilo_de_vida { get; set; }
    }
}
